# Form implementation generated from reading ui file 'lcd.ui'
#
# Created by: PyQt6 UI code generator 6.2.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Example(object):
    def setupUi(self, Example):
        Example.setObjectName("Example")
        Example.resize(206, 310)
        Example.setStyleSheet("background: lightgrey")
        self.verticalLayout = QtWidgets.QVBoxLayout(Example)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lcdNumber = QtWidgets.QLCDNumber(Example)
        self.lcdNumber.setStyleSheet("background: white")
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalLayout.addWidget(self.lcdNumber)
        self.dial = QtWidgets.QDial(Example)
        self.dial.setMaximum(255)
        self.dial.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.dial.setInvertedAppearance(False)
        self.dial.setNotchesVisible(True)
        self.dial.setObjectName("dial")
        self.verticalLayout.addWidget(self.dial)

        self.retranslateUi(Example)
        self.dial.valueChanged['int'].connect(self.lcdNumber.display) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Example)

    def retranslateUi(self, Example):
        _translate = QtCore.QCoreApplication.translate
        Example.setWindowTitle(_translate("Example", "QLCDNumber"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Example = QtWidgets.QWidget()
    ui = Ui_Example()
    ui.setupUi(Example)
    Example.show()
    sys.exit(app.exec())
